### ISSUE TITLE
Re-writing the IDE using a Javascript frontend

### ISSUE THREAD

**Issue by erezsh** [lark-parser/ide#3]
@Cerberus1746 I went over your svelte fork. I managed to get the monaco editor to work, but I couldn't find any way to run Python commands. Did you figure it out already, or is it still an open task?

**Comment by leandro-benedet-garcia** [comment]
@erezsh Still an open task.

Life caught up and stuff.

But checking the code I wrote, I did some bare bones work related to it, because I remember fixing problems with python itself and making it run, probably not with lark already, but I think the structure is there in load_python.js, which is the webservice that is running in a different thread.

**Comment by erezsh** [comment]
That's alright, I appreciate that you made the initial effort.

I'll try to get there on my own.

Btw Lark has a budget now, so worst case I can try to "outsource" the tricky parts.

**Comment by erezsh** [comment]
Done! :)
